export const ADD_COLLECTION = 'ADD_COLLECTION';
export const EDIT_COLLECTION = 'EDIT_COLLECTION';
export const DELETE_COLLECTION = 'DELETE_COLLECTION';
export const FETCH_COLLECTIONS = 'FETCH_COLLECTIONS';
